version: "2"
services:
  antidote1:
    image: mweber/antidotedb:latest
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
  antidote2:
    image: mweber/antidotedb:latest
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"

  link:
    image: erlang:19
    volumes:
      - .:/code
    command: '/code/link.sh'
    links:
      - antidote1
      - antidote2

  server1:
    image: node:latest
    ports:
      - "3000:3000"
    environment:
      - ANTIDOTE_HOST=antidote1
    volumes:
      - .:/code
    command: "node server.js"
    working_dir: /code
    links:
      - link

  server2:
    image: node:latest
    ports:
      - "3001:3000"
    environment:
      - ANTIDOTE_HOST=antidote2
    volumes:
      - .:/code
    command: "node server.js"
    working_dir: /code
    links:
      - link

  shell:
    image: node:latest
    volumes:
      - .:/local
    links:
      - link
